Removing CEETM compilation error due to change in prototypes of hlist_for_each_entry() and hlist_for_each_entry_safe() in linux-devel.
Variable of type struct hlist_node is now not passed as argument to
above mentioned functions.

Signed-off-by: Ganga Negi <ganga.negi@freescale.com>
Change-Id: Iacc238399cf25b6d4eee57c1d3666b778d04253f
Reviewed-on: http://git.am.freescale.net:8181/9927
Reviewed-by: Rajan Gupta <rajan.gupta@freescale.com>
Tested-by: Rajan Gupta <rajan.gupta@freescale.com>